# -*- coding: utf-8 -*-
"""upi_lab1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wuUb_ndOnMrNkDfk8cDB29ghT4OZvrs-
"""

def compare():
  print('Введите первое число:')
  a = int(input())
  print('Введите второе число:')
  b = int(input())
  lena = len(str(abs(a)))
  lenb = len(str(abs(b)))
  if lena > lenb:
    print('В первом числе больше цифр')
  elif lenb > lena:
    print('Во втором числе больше цифр')
  else:
    print('Количество цифр в обеих числах одинаково')

compare()
input()